# Generated by Django 3.1 on 2022-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timezone",
            name="value",
            field=models.FloatField(),
        ),
    ]
