# Generated by Django 3.1 on 2022-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapper", "0002_auto_20220418_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="is_valid_with_robots",
            field=models.BooleanField(default=True),
        ),
    ]
