# Generated by Django 3.1 on 2022-04-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapper", "0003_website_is_valid_with_robots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="scrapper.timezone",
            ),
        ),
    ]
