# Generated by Django 3.1 on 2022-04-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapper", "0004_auto_20220418_2030"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
